export {
  promptProfilesPageDisplay,
  promptModePresentation,
  promptProfilesPagePresentation,
  builtinProfilesPanelDisplay,
  profileDiagnoseDisplay,
  profileDiagnosePanelDisplay,
  customProfileDetectPanelDisplay,
  createProfileDiagnoseState,
} from "./promptProfileWorkspace.js";

export {
  builtinProfileDetectDetailsPresentation,
  builtinProfileHooksDetailsPresentation,
  builtinProfileStateListsPresentation,
  profileListRowEditorPresentation,
  profileInteractionRowEditorPresentation,
  profileTransitionRowEditorPresentation,
  profileHookRowEditorDisplay,
  profileHookFlowEditorDisplay,
  profileHookFlowStepsEditorDisplay,
  profilePatternListEditorDisplay,
  hookOperationEditorDisplay,
} from "./profilesEditor.js";

export { customProfileSettingsDisplay } from "./profilesCustomEditorState.js";

export {
  createPromptProfilesPageWorkspace,
  changeBuiltinProfileSelection,
  copySelectedBuiltinProfileToCustom,
  addProfileDetectProbe,
  addProfileDetectProbeErrorPattern,
  addProfileDetectInitialRule,
  addProfileDetectProbeRule,
  patchProfileDetectProbe,
  patchProfileDetectInitialRule,
  patchProfileDetectProbeRule,
  removeProfileDetectProbe,
  removeProfileDetectProbeErrorPattern,
  removeProfileDetectInitialRule,
  removeProfileDetectProbeRule,
  setProfileDetectEnabled,
  setProfileDetectProbeErrorPattern,
  builtinOverviewState,
  builtinDetailState,
  builtinDetailStatusState,
  profileDiagnoseOptionsState,
  profileDetectFormStateStore,
  executionModeOptionsVersion,
  MODE_SELECT,
  TEXTFSM_PLATFORM_SELECT,
  executionConnectionProfileState,
  modeSelection,
  textfsmPlatformSelection,
  refreshExecutionModeOptionsForCurrentConnection,
  setProfileDiagnoseSelected,
  diagnoseSelectedCustomProfile,
  ensureProfileDetectDefaults,
  builtinProfileForm,
  initializeProfiles,
  setNormalizedPromptMode,
  refreshPromptProfileLanguageOptions,
  loadProfilesOverview,
} from "./promptProfileWorkspace.js";

export {
  customProfileBaseState,
  customProfileOptionsState,
  customProfileStatusState,
  customProfileListSectionDisplays,
  customProfileHookSectionDisplays,
  hookModeOptionsVersion,
  profileListRowsState,
  hookListRowsState,
  builtinProfileFormValue,
  saveCustomProfile,
  deleteCustomProfile,
  createCustomProfileDraft,
  loadSelectedCustomProfile,
  updateCustomCommandExecutionMode,
  updateCustomShellExitMarker,
  patchProfileListRow,
  removeHookListFlowStep,
  removeHookListRow,
  removeProfileListPattern,
  removeProfileListRow,
  setProfileListPattern,
  setProfileListPatternState,
  setProfileListSimpleValue,
  addHookListFlowStep,
  addHookListRow,
  addProfileListItem,
  addProfileListPattern,
  changeHookListKind,
  patchHookListCommand,
  patchHookListFlow,
  patchHookListFlowStep,
  patchHookListRow,
} from "./profilesCustomEditorState.js";

export {
  builtinProfileReadonlyDisplay,
  profileHookCommandModePatch,
  profileHookCommandTextPatch,
  profileHookCommandTimeoutPatch,
  profileHookFlowMaxStepsPatch,
  profileHookFlowStepCommandPatch,
  profileHookFlowStepModePatch,
  profileHookFlowStepTimeoutPatch,
  profileHookFlowStopOnErrorPatch,
  profileHookRowFailurePolicyPatch,
  profileHookRowNamePatch,
  profileHookRowRecordOutputPatch,
  profileHookRowStatePatch,
  profileListRowFieldPatches,
} from "./profilesEditor.js";

export {
  createBuiltinProfileDetectSectionWorkspace,
  createBuiltinProfileHooksSectionWorkspace,
  createBuiltinProfileStateListsSectionWorkspace,
  createCustomProfileDetectPanelWorkspace,
  createCustomProfilesEditorWorkspace,
  createProfileDetectProbeCardWorkspace,
  createProfileDiagnosePanelWorkspace,
  createProfileHookRowEditorWorkspace,
  createProfileListRowEditorWorkspace,
} from "./profilePanelWorkspaces.js";
