import {
  createTemplateResource,
  deleteCustomShowObject,
  deleteTemplateResource,
  deleteTextfsmMapping,
  getInteractiveTemplate,
  getDeviceProfilesOverview,
  getProfileModes,
  getTemplateResource,
  inspectInteractiveTemplate,
  inspectCommandTemplate,
  listCustomShowObjects,
  listTemplateResource,
  listTextfsmMappings,
  saveCustomShowObject,
  saveTextfsmMapping,
  updateTemplateResource,
} from "../../../api/client.js";
import type { TemplateApi } from "../model/types.js";

export const templatesApi: TemplateApi = {
  createTemplateResource,
  deleteCustomShowObject,
  deleteTemplateResource,
  deleteTextfsmMapping,
  getInteractiveTemplate,
  getDeviceProfilesOverview,
  getProfileModes,
  getTemplateResource,
  inspectInteractiveTemplate,
  inspectCommandTemplate,
  listCustomShowObjects,
  listTemplateResource,
  listTextfsmMappings,
  saveCustomShowObject,
  saveTextfsmMapping,
  updateTemplateResource,
};
