name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build & Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: rauto
            asset_name: rauto-linux-amd64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: rauto
            asset_name: rauto-macos-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: rauto
            asset_name: rauto-macos-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: rauto.exe
            asset_name: rauto-windows-amd64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
            targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          cd target/${{ matrix.target }}/release
          tar -czf ../../../${{ matrix.asset_name }}.tar.gz ${{ matrix.artifact_name }}
          cd -

      - name: Package (Windows)
        if: runner.os == 'Windows'
        run: |
          cd target/${{ matrix.target }}/release
          7z a ../../../${{ matrix.asset_name }}.zip ${{ matrix.artifact_name }}
          cd -

      - name: Upload Release Asset (Linux/macOS)
        if: runner.os != 'Windows'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.asset_name }}.tar.gz

      - name: Upload Release Asset (Windows)
        if: runner.os == 'Windows'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.asset_name }}.zip
