name = "cisco_like_copy"
stop_on_error = true
default_mode = "Enable"

[[steps]]
timeout_secs = 300
command = "{{command}}"

[[steps.prompts]]
patterns = ["(?i)^Address or name of remote host.*\\?\\s*$"]
append_newline = true
record_input = true
response = "{{server_addr}}"

[[steps.prompts]]
patterns = ["(?i)^Source (?:file ?name|filename).*\\?\\s*$"]
append_newline = true
record_input = true
response = "{{remote_path}}"

[[steps.prompts]]
patterns = ["(?i)^Destination (?:file ?name|filename).*\\?\\s*$"]
append_newline = true
record_input = true
response = "{{remote_path}}"

[[steps.prompts]]
patterns = ["(?i)^Source username.*\\?\\s*$", "(?i)^Destination username.*\\?\\s*$"]
append_newline = true
record_input = true
response = "{{transfer_username}}"

[[steps.prompts]]
patterns = ["(?i)^.*password.*:\\s*$"]
append_newline = true
record_input = false
response = "{{transfer_password}}"

[[steps.prompts]]
patterns = ["(?i)^.*\\[confirm\\]\\s*$"]
append_newline = true
record_input = false
response = ""

[[steps.prompts]]
patterns = ["(?i)^.*(?:overwrite|over write).*\\[(?:y/n|yes/no)\\].*$"]
append_newline = true
record_input = false
response = "{{overwrite_answer}}"
