name = "linux_scp_with_current_and_peer"
stop_on_error = true
default_mode = "User"

[[steps]]
timeout_secs = 900
command = "scp {{local_path}} {{peer.username}}@{{peer.host}}:{{remote_path}}"

[[steps.prompts]]
patterns = ["(?i)^.*are you sure you want to continue connecting.*\\?\\s*$"]
append_newline = true
record_input = true
response = "yes"

[[steps.prompts]]
patterns = ["(?i)^.*password.*:\\s*$"]
append_newline = true
record_input = false
response = "{{peer.password}}"
